version: '3.8'

services:
  app:
    build:
      context: .
    depends_on:
      - redis
      - db
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=MovieDB;Username=postgres;Password=1234

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:17
    ports:
      - "5433:5432"  # Внешний порт 5433, внутренний порт 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: MovieDB
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:



