--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2 (Postgres.app)
-- Dumped by pg_dump version 17.2 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Reviews" (
    "Id" integer NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserId" integer NOT NULL,
    "MovieId" integer NOT NULL
);


ALTER TABLE public."Reviews" OWNER TO postgres;

--
-- Name: Reviews_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Reviews" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Reviews_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Username" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: movies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movies (
    "Id" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Genre" character varying(100) NOT NULL,
    "Year" integer NOT NULL,
    "Rating" double precision NOT NULL,
    "IsPublic" boolean DEFAULT false NOT NULL,
    "UserId" integer,
    "IsTopRated" boolean DEFAULT false NOT NULL
);


ALTER TABLE public.movies OWNER TO postgres;

--
-- Name: movies_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.movies ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."movies_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: Reviews; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Reviews" ("Id", "Rating", "Comment", "CreatedAt", "UserId", "MovieId") FROM stdin;
3	8	Отличный фильм!	2025-01-17 14:54:50.802092+03	1	1
4	8	Отличный фильм!	2025-01-17 15:16:48.894458+03	1	1
2	9	Понравился даже больше, чем в первый раз!	2025-01-17 15:36:16.775031+03	1	1
5	8	Отличный фильм!	2025-01-22 11:44:32.627668+03	2	1
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Username", "PasswordHash", "Role") FROM stdin;
1	testuser	$2a$11$bK8LoSQJT5LvvSAoMvIO4ebrPwqTSLTWF6XByV4HHszt3b/lRddnK	
2	testuser2	$2a$11$Mu0KXRfbe81WyZ9QZH9MieQQDzwF0wxxbiw69C4qGWCjb8CNF7CSS	User
3	admin123	$2a$11$UuOS5TBGecr4THdAIdL66.sD1VQASeQeZdBcVLubUY5gqADF5nUZG	Admin
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250110173035_InitialMigration	9.0.0
20250110201345_AddGetReviewsByMovieId	9.0.0
20250117183001_AddRoleToUser	9.0.1
20250119200726_AddRoleToUserUpdate	9.0.1
\.


--
-- Data for Name: movies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.movies ("Id", "Title", "Genre", "Year", "Rating", "IsPublic", "UserId", "IsTopRated") FROM stdin;
1	Updated Title	Drama	2023	9.5	f	1	f
2	gabela	Sci	2014	8.6	f	1	f
3	The Matrix	Action	1999	8.7	t	\N	t
4	The Mafia	Action	1989	9.7	t	\N	t
5	The Mafia	Action	1989	9.7	t	\N	t
6	gabela	Sci	2014	8.6	f	2	f
7	The Mafia	Action	1989	9.7	t	\N	t
\.


--
-- Name: Reviews_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Reviews_Id_seq"', 5, true);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 3, true);


--
-- Name: movies_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."movies_Id_seq"', 7, true);


--
-- Name: Reviews PK_Reviews; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reviews"
    ADD CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: movies PK_movies; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT "PK_movies" PRIMARY KEY ("Id");


--
-- Name: IX_Reviews_MovieId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Reviews_MovieId" ON public."Reviews" USING btree ("MovieId");


--
-- Name: IX_Reviews_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Reviews_UserId" ON public."Reviews" USING btree ("UserId");


--
-- Name: IX_movies_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_movies_UserId" ON public.movies USING btree ("UserId");


--
-- Name: Reviews FK_Reviews_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reviews"
    ADD CONSTRAINT "FK_Reviews_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: Reviews FK_Reviews_movies_MovieId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reviews"
    ADD CONSTRAINT "FK_Reviews_movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES public.movies("Id") ON DELETE CASCADE;


--
-- Name: movies FK_movies_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT "FK_movies_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

